### ISSUE TITLE
Issues with baseline scripts

### ISSUE THREAD

**Issue by qmeeus** [asappresearch/slue-toolkit#19]
Hi,

I am running into an error when trying to run the baseline script for voxpopuli:
```
Traceback (most recent call last):                                                                                                                                                                    
  File "~/bin/anaconda3/envs/fairseq/bin/fairseq-hydra-train", line 33, in <module>                                                                                       
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())                                                                                                                 
  File "~/repos/fairseq/fairseq_cli/hydra_train.py", line 87, in cli_main                                                                                                 
    hydra_main()                                                                                                                                                                                      
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main                                                               
    _run_hydra(                                                                                                                                                                                       
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra                                                       
    run_and_report(                                                                                                                                                                                   
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report                                                   
    raise ex                                                                                                                                                                                          
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report                                                   
    return func()                                                                                                                                                                                     
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>                                                         
    lambda: hydra.run(                                                                                                                                                                                
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run                                                              
    return run_job(                                                                                                                                                                                   
  File "~/bin/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job                                                               
    ret.return_value = task_function(task_cfg)                                                                                                                                                        
  File "~/repos/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main                                                                                               
    _hydra_main(cfg)                                                                                                                                                                                  
  File "~/repos/fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main                                                                                              
    distributed_utils.call_main(cfg, pre_main, **kwargs)                                                                                                                                              
  File "~/repos/fairseq/fairseq/distributed/utils.py", line 369, in call_main                                                                                             
    main(cfg, **kwargs)                                                                                                                                                                               
  File "~/repos/fairseq/fairseq_cli/train.py", line 164, in main                                                                                                          
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(                                                                                                                                        
  File "~/repos/fairseq/fairseq/checkpoint_utils.py", line 272, in load_checkpoint                                                                                        
    epoch_itr = trainer.get_train_iterator(                                                                                                                                                           
  File "~/repos/fairseq/fairseq/trainer.py", line 718, in get_train_iterator                                                                                              
    self.reset_dummy_batch(batch_iterator.first_batch)                                                                                                                                                
  File "~/repos/fairseq/fairseq/data/iterators.py", line 334, in first_batch                                                                                              
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])                                                                                                                         
  File "~/repos/fairseq/fairseq/data/add_target_dataset.py", line 68, in collater                                                                                         
    collated["net_input"]["prev_output_tokens"],                                                                                                                                                      
KeyError: 'prev_output_tokens'
```
I have installed fairseq as recommended on the github page. Here is the installed version:
```
fairseq                   1.0.0a0+0f078de           dev_0    <develop>                                                                                                                                
```
Any pointers to solve this error?

Thank you

**Comment by Splend1d** [comment]
Hi,
I was able to solve this error by installing a previous fairseq commit : 
[Prosody-aware Generative Spoken Language Modelling (#3063) ]
SHA : 0c0ef06780b121b2b50b271852bde88fc998936e
Hope this may help!
