### ISSUE TITLE
wav2letter installation error!

### ISSUE THREAD

**Issue by sameerkhurana10** [asappresearch/slue-toolkit#30]
Does anyone know how to fix the below error when installing wav2letter python bindings

```
Obtaining file:///gpfsssd/scratch/rech/iqh/upp27cx/wav2letter/bindings/python
  Preparing metadata (setup.py) ... done
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [48 lines of output]
        running develop
        running egg_info
        writing wav2letter.egg-info/PKG-INFO
        writing dependency_links to wav2letter.egg-info/dependency_links.txt
        writing top-level names to wav2letter.egg-info/top_level.txt
        reading manifest file 'wav2letter.egg-info/SOURCES.txt'
        writing manifest file 'wav2letter.egg-info/SOURCES.txt'
        running build_ext
        gmake: Makefile: No such file or directory
        gmake: *** No rule to make target 'Makefile'.  Stop.
        /gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated.
 Use build and pip and other standards-based tools.
          warnings.warn(
        /gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build
and pip and other standards-based tools.
          warnings.warn(
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/gpfsssd/scratch/rech/iqh/upp27cx/wav2letter/bindings/python/setup.py", line 95, in <module>
            setup(
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
            return run_commands(dist)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
            dist.run_commands()
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
            self.run_command(cmd)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
            self.distribution.run_command(command)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
            cmd_obj.run()
          File "/gpfsssd/scratch/rech/iqh/upp27cx/wav2letter/bindings/python/setup.py", line 48, in run
            self.build_extensions()
          File "/gpfsssd/scratch/rech/iqh/upp27cx/wav2letter/bindings/python/setup.py", line 90, in build_extensions
            subprocess.check_call(
          File "/gpfswork/rech/iqh/upp27cx/conda-envs/fairseq_a100_clone_jan9/lib/python3.8/subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sshon-asapp** [comment]
Which wav2letter commit are you using?
I succeeded with commit `6fdb54bbc37938c1663d9d263a3d33a5cc3168d9`
Try with this commit.

**Comment by sameerkhurana10** [comment]
Still the same prob. I will try to create my own pipeline without wav2letter decoder. wav2letter has always given me problems
